spring.security.user.name=${SPRING_SECURITY_USER_NAME}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD}
spring.security.user.roles=${SPRING_SECURITY_USER_ROLES}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
