spring.security.user.name=${SPRING_SECURITY_USER}
spring.security.user.password=${SPRING_SECURITY_PASSWORD}
spring.security.user.roles=${SPRING_SECURITY_ROLES}

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
